server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # React Router client-side routing: bilinmeyen path'ler index.html'e düşsün
    location / {
        try_files $uri $uri/ /index.html;
    }
}
